import 'package:flutter/material.dart';
import './models/item.dart';

var DUMMY_ITEMS = [
  Item(
    id: "i1",
    name: "Cola",
    price: 100.000,
    stock: 5,
    img: "assets/images/cola.jpg",
    itemType: "Drink",
  ),
  Item(
    id: "i1",
    name: "Cola",
    price: 100.000,
    stock: 5,
    img: "assets/images/cola.jpg",
    itemType: "Drink",
  ),
  Item(
    id: "i1",
    name: "Cola",
    price: 100.000,
    stock: 5,
    img: "assets/images/cola.jpg",
    itemType: "Drink",
  ),
  Item(
    id: "i1",
    name: "Cola",
    price: 100.000,
    stock: 5,
    img: "assets/images/cola.jpg",
    itemType: "Drink",
  ),
  Item(
    id: "i1",
    name: "Cola",
    price: 100.000,
    stock: 5,
    img: "assets/images/cola.jpg",
    itemType: "Drink",
  ),
  Item(
    id: "i1",
    name: "Cola",
    price: 100.000,
    stock: 5,
    img: "assets/images/cola.jpg",
    itemType: "Drink",
  ),
  Item(
    id: "i1",
    name: "Cola",
    price: 100.000,
    stock: 5,
    img: "assets/images/cola.jpg",
    itemType: "Drink",
  ),
  Item(
      id: "i1",
      name: "Cola",
      price: 100.000,
      stock: 5,
      img: "assets/images/cola.jpg"),
  Item(
      id: "i1",
      name: "Cola",
      price: 100.000,
      stock: 5,
      img: "assets/images/cola.jpg"),
  Item(
      id: "i1",
      name: "Cola",
      price: 100.000,
      stock: 5,
      img: "assets/images/cola.jpg"),
  Item(
      id: "i1",
      name: "Cola",
      price: 100.000,
      stock: 5,
      img: "assets/images/cola.jpg"),
  Item(
      id: "i1",
      name: "Cola",
      price: 100.000,
      stock: 5,
      img: "assets/images/cola.jpg"),
  Item(
      id: "i2",
      name: "Xuc xich",
      price: 150.000,
      stock: 5,
      img: "assets/images/xucxich.jpg"),
  Item(
      id: "i2",
      name: "Xuc xich",
      price: 150.000,
      stock: 5,
      img: "assets/images/xucxich.jpg"),
  Item(
      id: "i2",
      name: "Xuc xich",
      price: 150.000,
      stock: 5,
      img: "assets/images/xucxich.jpg"),
  Item(
      id: "i2",
      name: "Xuc xich",
      price: 150.000,
      stock: 5,
      img: "assets/images/xucxich.jpg"),
  Item(
      id: "i2",
      name: "Xuc xich",
      price: 150.000,
      stock: 5,
      img: "assets/images/xucxich.jpg"),
  Item(
      id: "i2",
      name: "Xuc xich",
      price: 150.000,
      stock: 5,
      img: "assets/images/xucxich.jpg"),
  Item(
      id: "i2",
      name: "Xuc xich",
      price: 150.000,
      stock: 5,
      img: "assets/images/xucxich.jpg"),
];
